name: Push on 1.4 jobs

on:
  push:
    branches: [ 1.4 ]

jobs:
  AutomaticPublishOriginal:
    if: false
    name: Automatic Mod Browser Publish Integration
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
       
      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
       
      - name: Setup steamcmd
        id: setupsteam
        uses: CyberAndrii/setup-steamcmd@v1
       
      # Mod Browser integration
      - uses: JavidPack/tModLoaderPublishIntegration@1.4
        with:
          STEAMID64: ${{secrets.STEAMID64}}
          MODBROWSERPASSPHRASE: ${{secrets.MODBROWSERPASSPHRASE}}
          MODNAME: BossChecklist
        
      # Upload artifact for all builds
      - uses: actions/upload-artifact@v2
        with:
          name: .tmod file
          path: ~/tModLoader/ModLoader/Mods/BossChecklist.tmod

  AutomaticPublishOriginalReusable:
    uses: JavidPack/tModLoaderPublishIntegration/.github/workflows/BuildAndPublishMod.yml@1.4
    with:
      testInput: This Is Test Input
    secrets:
      testsecret: ThisIsATestSecret